### ISSUE TITLE
CUDA 10

### ISSUE THREAD

**Issue by vasanththangavel** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#98]
@yangxue0827 I have installed cuda 10.0 on my system,it works fine but  while training it shows no CUDA-capable device is detected and runs on cpu

**Comment by vasanththangavel** [comment]
In train.py , i made this change os.environ["CUDA_VISIBLE_DEVICES"] = '0', then it works in GPU, But it tooks so much time to train

**Comment by yangxue0827** [comment]
multi-gpu training is suppport, please refer [here](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/master/tools/multi_gpu_train.py).
@vasanththangavel
